<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTableAirports extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('airports', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code');
            $table->string('name');
        });

        DB::statement("INSERT INTO airports (id, code, name) VALUES
            (1, 'ABE', 'Allentown'),
            (2, 'ABQ', 'Albuquerque International Airport'),
            (3, 'ACK', 'Nantucket'),
            (4, 'ACY', 'Atlantic City International Airport'),
            (5, 'AGS', 'Augusta'),
            (6, 'ALB', 'Albany International Airport'),
            (7, 'ALM', 'Alamogordo'),
            (8, 'AMA', 'Amarillo'),
            (9, 'ANC', 'Anchorage International Airport'),
            (10, 'ASE', 'Aspen'),
            (11, 'ATL', 'Atlanta Hartsfield International Airport'),
            (12, 'AUG', 'Augusta'),
            (13, 'AUS', 'Austin Bergstrom International Airport'),
            (14, 'AVL', 'Asheville'),
            (15, 'AVP', 'Scranton'),
            (16, 'AZO', 'Kalamazoo-Battle Creek International Airport'),
            (17, 'BDL', 'Hartford'),
            (18, 'BGR', 'Bangor'),
            (19, 'BHM', 'Birmingham International Airport'),
            (20, 'BIL', 'Billings'),
            (21, 'BIS', 'Bismark'),
            (22, 'BNA', 'Nashville'),
            (23, 'BOI', 'Boise'),
            (24, 'BOS', 'Boston, Logan International Airport'),
            (25, 'BTL', 'Battlecreek'),
            (26, 'BTR', 'Baton Rouge'),
            (27, 'BTV', 'Burlington'),
            (28, 'BUF', 'Buffalo'),
            (29, 'BUR', 'Burbank'),
            (30, 'BWI', 'Baltimore'),
            (31, 'CAE', 'Columbia'),
            (32, 'CAK', 'Akron'),
            (33, 'CHA', 'Chattanooga'),
            (34, 'CHS', 'Charleston'),
            (35, 'CID', 'Cedar Rapids'),
            (36, 'CKB', 'Clarksburg'),
            (37, 'CLE', 'Cleveland'),
            (38, 'CLT', 'Charlotte/Douglas International Airport'),
            (39, 'CMH', 'Columbus'),
            (40, 'COS', 'Colorado Springs'),
            (41, 'CPR', 'Casper'),
            (42, 'CRP', 'Corpus Christi'),
            (43, 'CRW', 'Charleston'),
            (44, 'CVG', 'Cincinnati'),
            (45, 'CYS', 'Cheyenne'),
            (46, 'DAB', 'Daytona Beach'),
            (47, 'DAL', 'Dallas Love Field Airport'),
            (48, 'DAY', 'Dayton'),
            (49, 'DCA', 'Washington National Airport'),
            (50, 'DEN', 'Denver International Airport'),
            (51, 'DET', 'Detroit'),
            (52, 'DFW', 'Dallas/Fort Worth International Airport'),
            (53, 'DHN', 'Dothan Regional Airport'),
            (54, 'DLH', 'Duluth'),
            (55, 'DSM', 'Des Moines'),
            (56, 'DTW', 'Detroit Metropolitan Airport'),
            (57, 'ELP', 'El Paso'),
            (58, 'ERI', 'Erie'),
            (59, 'EUG', 'Eugene'),
            (60, 'EVV', 'Evansville'),
            (61, 'EWR', 'Newark International Airport'),
            (62, 'EYW', 'Key West International Airport'),
            (63, 'FAI', 'Fairbanks International Airport'),
            (64, 'FAR', 'Fargo'),
            (65, 'FAT', 'Fresno'),
            (66, 'FAY', 'Fayetteville'),
            (67, 'FLG', 'Flagstaff'),
            (68, 'FLL', 'Fort Lauderdale-Hollywood International Airport'),
            (69, 'FNT', 'Flint'),
            (70, 'FSD', 'Sioux Falls'),
            (71, 'FWA', 'Fort Wayne'),
            (72, 'FYV', 'Fayetteville'),
            (73, 'GEG', 'Spokane International Airport'),
            (74, 'GJT', 'Grand Junction'),
            (75, 'GPT', 'Gulfport'),
            (76, 'GRB', 'Green Bay'),
            (77, 'GRR', 'Grand Rapids'),
            (78, 'GSO', 'Greensboro'),
            (79, 'GSP', 'Greenville'),
            (80, 'HIO', 'Portland, Hillsboro Airport'),
            (81, 'HNL', 'Honolulu International Airport'),
            (82, 'HOU', 'Houston, William B Hobby Airport'),
            (83, 'HPN', 'Westchester'),
            (84, 'HSV', 'Huntsville International Airport'),
            (85, 'HYA', 'Hyannis'),
            (86, 'IAD', 'Dulles'),
            (87, 'IAD', 'Washington, Dulles International Airport'),
            (88, 'IAH', 'Houston, George Bush Intercontinental Airport'),
            (89, 'ICT', 'Wichita'),
            (90, 'IND', 'Indianapolis International Airport'),
            (91, 'INT', 'Winston-Salem'),
            (92, 'ISP', 'Islip'),
            (93, 'ITO', 'Hilo'),
            (94, 'JAC', 'Jackson Hole'),
            (95, 'JAN', 'Jackson'),
            (96, 'JAX', 'Jacksonville'),
            (97, 'JFK', 'New York, John F Kennedy International Airport'),
            (98, 'JNU', 'Juneau International Airport'),
            (99, 'KOA', 'Kailua'),
            (100, 'LAN', 'Lansing'),
            (101, 'LAS', 'Las Vegas, Las Vegas McCarran International Airport'),
            (102, 'LAX', 'Los Angeles International Airport'),
            (103, 'LBB', 'Lubbock'),
            (104, 'LEX', 'Lexington'),
            (105, 'LGA', 'New York, La Guardia Airport'),
            (106, 'LGB', 'Long Beach'),
            (107, 'LIH', 'Lihue'),
            (108, 'LIT', 'Little Rock National Airport'),
            (109, 'LNK', 'Lincoln'),
            (110, 'MAF', 'Midland'),
            (111, 'MBS', 'Saginaw'),
            (112, 'MCI', 'Kansas City'),
            (113, 'MCO', 'Orlando'),
            (114, 'MDT', 'Harrisburg'),
            (115, 'MDW', 'Chicago Midway Airport'),
            (116, 'MEM', 'Memphis'),
            (117, 'MGM', 'Montgomery'),
            (118, 'MHT', 'Manchester'),
            (119, 'MIA', 'Miami International Airport'),
            (120, 'MKE', 'Milwaukee'),
            (121, 'MLI', 'Moline'),
            (122, 'MOB', 'Mobile'),
            (123, 'MPV', 'Montpelier'),
            (124, 'MSN', 'Madison'),
            (125, 'MSP', 'Minneapolis/St.Paul International Airport'),
            (126, 'MSY', 'New Orleans International Airport'),
            (127, 'MYR', 'Myrtle Beach'),
            (128, 'OAK', 'Oakland'),
            (129, 'OGG', 'Kahului'),
            (130, 'OKC', 'Oklahoma City'),
            (131, 'OMA', 'Omaha'),
            (132, 'ONT', 'Ontario'),
            (133, 'ORD', 'Chicago, O''Hare International Airport Airport'),
            (134, 'ORF', 'Norfolk'),
            (135, 'ORH', 'Worcester'),
            (136, 'PBI', 'West Palm Beach'),
            (137, 'PDX', 'Portland International Airport'),
            (138, 'PFN', 'Panama City-Bay County International Airport'),
            (139, 'PHF', 'Newport News'),
            (140, 'PHL', 'Philadelphia'),
            (141, 'PHX', 'Phoenix, Phoenix Sky Harbor International Airport'),
            (142, 'PIA', 'Peoria'),
            (143, 'PIE', 'St. Petersburg'),
            (144, 'PIR', 'Pierre'),
            (145, 'PIT', 'Pittsburgh'),
            (146, 'PNS', 'Pensacola'),
            (147, 'PSC', 'Pasco, Pasco/Tri-Cities Airport'),
            (148, 'PSP', 'Palm Springs'),
            (149, 'PUB', 'Pueblo'),
            (150, 'PVD', 'Providence - T.F. Green Airport'),
            (151, 'PWM', 'Portland'),
            (152, 'RAP', 'Rapid City'),
            (153, 'RDU', 'Raleigh'),
            (154, 'RIC', 'Richmond'),
            (155, 'RKS', 'Rock Springs'),
            (156, 'RNO', 'Reno-Tahoe International Airport'),
            (157, 'ROA', 'Roanoke'),
            (158, 'ROC', 'Rochester'),
            (159, 'RST', 'Rochester'),
            (160, 'RSW', 'Fort Meyers'),
            (161, 'RUT', 'Rutland'),
            (162, 'SAN', 'San Diego'),
            (163, 'SAT', 'San Antonio International Airport'),
            (164, 'SAV', 'Savannah'),
            (165, 'SBN', 'South Bend'),
            (166, 'SDF', 'Louisville'),
            (167, 'SEA', 'Seattle, Tacoma International Airport'),
            (168, 'SFO', 'San Francisco International Airport'),
            (169, 'SGF', 'Springfield'),
            (170, 'SHV', 'Shreveport'),
            (171, 'SJC', 'San Jose'),
            (172, 'SLC', 'Salt Lake City'),
            (173, 'SLE', 'Salem'),
            (174, 'SMF', 'Sacramento'),
            (175, 'SNA', 'Santa Ana'),
            (176, 'SRQ', 'Sarasota'),
            (177, 'STL', 'St Louis, Lambert International Airport'),
            (178, 'SWF', 'Newburgh'),
            (179, 'SYR', 'Syracuse'),
            (180, 'TOL', 'Toledo'),
            (181, 'TPA', 'Tampa'),
            (182, 'TRI', 'Bristol'),
            (183, 'TTN', 'Trenton'),
            (184, 'TUL', 'Tulsa'),
            (185, 'TUS', 'Tucson International Airport'),
            (186, 'TYS', 'Knoxville'),
            (187, 'YUM', 'Yuma International Airport')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('airports');
    }
}
